security:
    providers:
        db_provider:
          entity:
            class: AppBundle:Users
            property: userName
    encoders:
        AppBundle\Entity\User:
          algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            form_login:
              login_path: /login
              check_path:  /login_check
            logout:
              path: /quit
              target: /
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: [ROLE_ADMIN,ROLE_USER] }