security:
    firewalls:
        secured_area:
            pattern:    ^/
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
            logout:
                 path: /quit
                 target: /

    access_control:
        - { path: ^/adminpage, roles: ROLE_ADMIN }
        - { path: ^/userpage, roles: [ROLE_ADMIN,ROLE_USER] }
        - { path: ^/artspage, roles: [ROLE_ADMIN, ROLE_ARTS] }

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
    providers:
        db_provider:
            entity:
                class: AppBundle:User
                property: userName